In [3]:
import numpy as np

# Indexing & slicing
scores = np.array([89, 72, 94, 65, 88])
print("Top 3 scores:", scores[:3])


Top 3 scores: [89 72 94]


In [4]:
# Boolean filtering — real world example (students passed)
passed = scores[scores >= 75]
print("Students who passed:", passed)

Students who passed: [89 94 88]


In [5]:
# Reshape
X = np.array([[1, 2], [3, 4], [5, 6]])
print("Shape:", X.shape)
print("Reshaped to (2, 3):\n", X.reshape(2, 3))
print("Flatten:", X.flatten())

Shape: (3, 2)
Reshaped to (2, 3):
 [[1 2 3]
 [4 5 6]]
Flatten: [1 2 3 4 5 6]


In [6]:
# Stacking feature arrays
feature1 = np.array([160, 170, 175])
feature2 = np.array([50, 65, 72])
dataset = np.vstack([feature1, feature2]).T   # ML-style feature matrix
print("Dataset with features:\n", dataset)


Dataset with features:
 [[160  50]
 [170  65]
 [175  72]]
