In [2]:
import numpy as np

# Dataset: Height (cm), Weight (kg), Age, Calories burned/day
data = np.array([
    [165, 58, 21, 1900],
    [175, 72, 25, 2300],
    [180, 85, 30, 2600],
    [160, 50, 19, 1700],
    [170, 65, 24, 2100],
])
data

array([[ 165,   58,   21, 1900],
       [ 175,   72,   25, 2300],
       [ 180,   85,   30, 2600],
       [ 160,   50,   19, 1700],
       [ 170,   65,   24, 2100]])

In [3]:
# ---------- 1. Extract features & target ----------
X = data[:, :3]   # features
y = data[:, 3]    # target
print("Features:\n", X)
print("Target:", y)


Features:
 [[165  58  21]
 [175  72  25]
 [180  85  30]
 [160  50  19]
 [170  65  24]]
Target: [1900 2300 2600 1700 2100]


In [4]:
# ---------- 2. Normalize features (ML preprocessing) ----------
X_norm = (X - X.mean(axis=0)) / X.std(axis=0)
print("Normalized Features:\n", X_norm)

Normalized Features:
 [[-0.70710678 -0.66759453 -0.7440916 ]
 [ 0.70710678  0.50069589  0.3188964 ]
 [ 1.41421356  1.585537    1.64763141]
 [-1.41421356 -1.33518905 -1.27558561]
 [ 0.         -0.08344932  0.0531494 ]]


In [5]:
# ---------- 3. Train/Test split ----------
np.random.seed(42)
indices = np.random.permutation(len(data))
train_size = int(0.8 * len(data))
train_idx, test_idx = indices[:train_size], indices[train_size:]

In [6]:
X_train, X_test = X_norm[train_idx], X_norm[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("Train X:\n", X_train)
print("Train y:", y_train)
print("Test X:\n", X_test)
print("Test y:", y_test)


Train X:
 [[ 0.70710678  0.50069589  0.3188964 ]
 [ 0.         -0.08344932  0.0531494 ]
 [ 1.41421356  1.585537    1.64763141]
 [-0.70710678 -0.66759453 -0.7440916 ]]
Train y: [2300 2100 2600 1900]
Test X:
 [[-1.41421356 -1.33518905 -1.27558561]]
Test y: [1700]
